### ISSUE TITLE
Packages are installed before preferences are deployed

### ISSUE THREAD

**Issue by EugenMayer** [manala/ansible-role-apt#10]
Lets assume you want to install the newst shorewall 5.0.x on debian due to its docker support,

you would go like this

```

manala_apt_repositories:
  - source: deb http://ftp.de.debian.org/debian/ unstable main

manala_apt_preferences:
  - package: '*'
    pin: release o=Debian,a=stable
    priority: 600
    file: stable
  - package: testing
    pin: release o=Debian,a=testing
    priority: -1
    file: testing
  - package: unstable
    pin: release o=Debian,a=unstable
    priority: -1
    file: unstable
  - package: 'shorewall*'
    pin: release o=Debian,a=unstable
    priority: 900
    file: shorewall

manala_apt_packages:
  - shorewall
```

the issue is, that 4.6.4.3-2 will be installed on jessie, eventhough after the deployment, doing 

```
 apt-cache policy shorewall
shorewall:
  Installed: 4.6.4.3-2
  Candidate: 5.0.14.1-1
  Package pin: 5.0.14.1-1
  Version table:
     5.0.14.1-1 900
        500 http://ftp.de.debian.org/debian/ unstable/main amd64 Packages
 *** 4.6.4.3-2 900
        600 http://deb.debian.org/debian/ jessie/main amd64 Packages
        100 /var/lib/dpkg/status
```

That means, that the preferences were deployed after the package was installed, which is not optimal at all, isnt it?
